# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.CharField(max_length=1)),
                ('grade', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('club', models.CharField(max_length=100)),
                ('zekken', models.BooleanField()),
                ('jacket', models.BooleanField()),
                ('joined', models.DateField()),
            ],
        ),
    ]
