# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20171022_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.CharField(choices=[('-', '-'), ('6K', '6. Kyu'), ('5K', '5. Kyu'), ('4K', '4. Kyu'), ('3K', '3. Kyu'), ('2K', '2. Kyu'), ('1K', '1. Kyu'), ('1D', '1. Dan'), ('2D', '2. Dan'), ('3D', '3. Dan'), ('4D', '4. Dan'), ('5D', '5. Dan'), ('6D', '6. Dan'), ('7D', '7. Dan'), ('8D', '8. Dan')], max_length=10),
        ),
    ]
