# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('member', '0006_auto_20171107_2104'), ('member', '0007_auto_20171107_2128')]

    dependencies = [
        ('member', '0005_auto_20171022_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ManyToManyField(to='member.Group'),
        ),
    ]
