# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20171107_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ManyToManyField(to='member.Group'),
        ),
    ]
